---
# Codacy configuration for KaasproFoods project
# Suppress false-positive security warnings for development/test files

# Exclude development and test files from security analysis
exclude_paths:
  # Backend development scripts - use hardcoded paths by design
  - 'backend-api/test-order.js'
  - 'backend-api/run-migration.js'
  - 'backend-api/run-migration-tables.js'
  - 'backend-api/src/database/init.js'

  # Frontend test files
  - 'delivery-app/test-connection.js'

  # Backend server file with Node.js API usage (false positive for Object.keys)
  - 'backend-api/src/server.js'

# Engine-specific configurations
engines:
  # ESLint security plugin
  eslint:
    # Disable security rules for backend development scripts
    exclude_patterns:
      - 'backend-api/test-*.js'
      - 'backend-api/run-*.js'
      - 'backend-api/src/database/init.js'
      - 'backend-api/src/server.js'
